version: '3.7'

services:
    db:
        image: "mcr.microsoft.com/mssql/server"
        ports:
            - 1444:1444
        volumes:             
            - ./init:/docker-entrypoint-initdb.d
        environment:
            SA_PASSWORD: "password123!"
            ACCEPT_EULA: "Y"  
